# .github/FUNDING.yml

github: clutch2sft

# If you later add other platforms, you can extend this, for example:
# patreon: your-patreon-username
# ko_fi: your-kofi-username
# open_collective: your-collective-name
# custom:
#   - https://your-website.example/sponsor
